server:
  address: 0.0.0.0
  port: 9094


spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

minio:
  endpoint: http://192.168.44.129:9000/
  accessKey: minioadmin
  secretKey: minioadmin

logging:
  level:
    root: info
    com.minio.minio_test: debug
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

