spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://124.70.53.210:9080
  accessKey: minio_user
  secretKey: 528528528

server:
  address: 0.0.0.0
  port: 9093


config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: token
